### ISSUE TITLE
AttributeError: 'Server' object has no attribute 'placement_group'

### ISSUE THREAD

**Issue by 0boro** [ansible-collections/hetzner.hcloud#104]
##### SUMMARY

After upgrading the collection dependencies of my project, i was trying to deploy/upgrading via Ansible and ran into this issue
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
hcloud_server

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = /home/xxx/projects/yyy/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/.local/lib/python3.9/site-packages/ansible
  executable location = /home/xxx/.local/bin/ansible
  python version = 3.9.6 (default, Jul  6 2021, 18:29:50) [GCC 10.2.1 20201203]
```

##### COLLECTION VERSION

```paste below
# /usr/lib/python3.9/site-packages/ansible_collections
Collection     Version
-------------- -------
hetzner.hcloud 1.2.0

# /home/xxx/.ansible/collections/ansible_collections
Collection     Version
-------------- -------
hetzner.hcloud 1.6.0

# /home/xxx/.local/lib/python3.9/site-packages/ansible_collections
Collection     Version
-------------- -------
hetzner.hcloud 1.2.1
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/xxx/projects/yyy/ansible.cfg) = True
DEFAULT_REMOTE_USER(/home/xxx/projects/yyy/ansible.cfg) = root
INTERPRETER_PYTHON(/home/xxx/projects/yyy/ansible.cfg) = /usr/bin/python3
```

##### STEPS TO REPRODUCE

Executing of the following yaml code

```yaml
- name: Ensure yyy exists on Hetzner
  gather_facts: false
  connection: local
  hosts: localhost
  tasks:
    - name: Ensure yyy server is created
      hcloud_server:
        name: "{{ server_name }}"
        server_type: cx21
        image: ubuntu-20.04
        user_data: "#include https://get.docker.com"
        location: fsn1
        ssh_keys:
          - "zzz"
        labels:
          yyy: ""
          environment: "{{ env }}"
        state: started
        api_token: "{{ lookup('env','HCLOUD_TOKEN') }}"
      register: _create_server
```

##### EXPECTED RESULTS

In my case, i was was doing a upgrade, so the server should already be there and the module should return ok
##### ACTUAL RESULTS

```paste below
TASK [Ensure yyy server is created] ****************************************************************************************************************************************************************************
task path: /home/xxx/projects/yyy/yyy.yml:7
redirecting (type: modules) ansible.builtin.hcloud_server to hetzner.hcloud.hcloud_server
Using module file /home/xxx/.ansible/collections/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py
Pipelining is enabled.
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: xxx
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_hcloud_server_payload_9uwj92gp/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 538, in _update_server
  File "/usr/lib/python3.9/site-packages/hcloud/core/client.py", line 103, in __getattr__
    value = getattr(self.data_model, name)
AttributeError: 'Server' object has no attribute 'placement_group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_hcloud_server_payload_9uwj92gp/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 739, in <module>
  File "/tmp/ansible_hcloud_server_payload_9uwj92gp/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 722, in main
  File "/tmp/ansible_hcloud_server_payload_9uwj92gp/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 662, in present_server
  File "/tmp/ansible_hcloud_server_payload_9uwj92gp/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 589, in _update_server
AttributeError: 'AttributeError' object has no attribute 'message'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_hcloud_server_payload_9uwj92gp/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 538, in _update_server\n  File \"/usr/lib/python3.9/site-packages/hcloud/core/client.py\", line 103, in __getattr__\n    value = getattr(self.data_model, name)\nAttributeError: 'Server' object has no attribute 'placement_group'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_hcloud_server_payload_9uwj92gp/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 739, in <module>\n  File \"/tmp/ansible_hcloud_server_payload_9uwj92gp/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 722, in main\n  File \"/tmp/ansible_hcloud_server_payload_9uwj92gp/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 662, in present_server\n  File \"/tmp/ansible_hcloud_server_payload_9uwj92gp/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 589, in _update_server\nAttributeError: 'AttributeError' object has no attribute 'message'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by Adi146** [comment]
Hi, did you upgrade the hcloud python package aswell?

**Comment by 0boro** [comment]
Upgraded it from 1.12.0 to 1.16.0, that fixed it.
Thank you @Adi146  for fixing my dependency chain :+1:
