### ISSUE TITLE
Firewalls can not be created

### ISSUE THREAD

**Issue by rommelfreddy** [ansible-collections/hetzner.hcloud#109]
##### SUMMARY

Firewall rules can not be created

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hcloud_firewall

##### ANSIBLE VERSION

```paste below
2.11.2
```

##### COLLECTION VERSION

```paste below
1.6.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Mac OS 11.3.1 (Big Sur)

##### STEPS TO REPRODUCE

Just use the following task:

```yaml
- name: Create a firewall for DATA-Servers
  hetzner.hcloud.hcloud_firewall:
    name: "Firewall for DATA-Servers"
    state: present
    rules:
      - direction: in
        protocol: tcp
        port: '22'
        source_ips:
          - XXX.XXX.XXX.XXX/32
```

##### EXPECTED RESULTS

Firewall got created

##### ACTUAL RESULTS

The following error will occur:

```paste below
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: freddyrommel
<127.0.0.1> EXEC /bin/sh -c 'echo ~freddyrommel && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/freddyrommel/.ansible/tmp `"&& mkdir "` echo /Users/freddyrommel/.ansible/tmp/ansible-tmp-1630654739.9226-71754-135403374808818 `" && echo ansible-tmp-1630654739.9226-71754-135403374808818="` echo /Users/freddyrommel/.ansible/tmp/ansible-tmp-1630654739.9226-71754-135403374808818 `" ) && sleep 0'
Using module file /Users/freddyrommel/.ansible/collections/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_firewall.py
<127.0.0.1> PUT /Users/freddyrommel/.ansible/tmp/ansible-local-717482gamxzde/tmpb6u951j4 TO /Users/freddyrommel/.ansible/tmp/ansible-tmp-1630654739.9226-71754-135403374808818/AnsiballZ_hcloud_firewall.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/freddyrommel/.ansible/tmp/ansible-tmp-1630654739.9226-71754-135403374808818/ /Users/freddyrommel/.ansible/tmp/ansible-tmp-1630654739.9226-71754-135403374808818/AnsiballZ_hcloud_firewall.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/Cellar/ansible/4.2.0/libexec/bin/python3.9 /Users/freddyrommel/.ansible/tmp/ansible-tmp-1630654739.9226-71754-135403374808818/AnsiballZ_hcloud_firewall.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/freddyrommel/.ansible/tmp/ansible-tmp-1630654739.9226-71754-135403374808818/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/Users/freddyrommel/.ansible/tmp/ansible-tmp-1630654739.9226-71754-135403374808818/AnsiballZ_hcloud_firewall.py", line 100, in <module>
    _ansiballz_main()
  File "/Users/freddyrommel/.ansible/tmp/ansible-tmp-1630654739.9226-71754-135403374808818/AnsiballZ_hcloud_firewall.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/freddyrommel/.ansible/tmp/ansible-tmp-1630654739.9226-71754-135403374808818/AnsiballZ_hcloud_firewall.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_firewall', init_globals=dict(_module_fqn='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_firewall', _modlib_path=modlib_path),
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/nh/8ttzxlg51ngd0cn235m4gsbc0000gn/T/ansible_hetzner.hcloud.hcloud_firewall_payload_kh0ed1__/ansible_hetzner.hcloud.hcloud_firewall_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_firewall.py", line 344, in <module>
  File "/var/folders/nh/8ttzxlg51ngd0cn235m4gsbc0000gn/T/ansible_hetzner.hcloud.hcloud_firewall_payload_kh0ed1__/ansible_hetzner.hcloud.hcloud_firewall_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_firewall.py", line 338, in main
  File "/var/folders/nh/8ttzxlg51ngd0cn235m4gsbc0000gn/T/ansible_hetzner.hcloud.hcloud_firewall_payload_kh0ed1__/ansible_hetzner.hcloud.hcloud_firewall_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_firewall.py", line 286, in present_firewall
  File "/var/folders/nh/8ttzxlg51ngd0cn235m4gsbc0000gn/T/ansible_hetzner.hcloud.hcloud_firewall_payload_kh0ed1__/ansible_hetzner.hcloud.hcloud_firewall_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_firewall.py", line 230, in _create_firewall
  File "/var/folders/nh/8ttzxlg51ngd0cn235m4gsbc0000gn/T/ansible_hetzner.hcloud.hcloud_firewall_payload_kh0ed1__/ansible_hetzner.hcloud.hcloud_firewall_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_firewall.py", line 231, in <listcomp>
TypeError: __init__() got an unexpected keyword argument 'description'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/freddyrommel/.ansible/tmp/ansible-tmp-1630654739.9226-71754-135403374808818/AnsiballZ_hcloud_firewall.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/Users/freddyrommel/.ansible/tmp/ansible-tmp-1630654739.9226-71754-135403374808818/AnsiballZ_hcloud_firewall.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/freddyrommel/.ansible/tmp/ansible-tmp-1630654739.9226-71754-135403374808818/AnsiballZ_hcloud_firewall.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_firewall', init_globals=dict(_module_fqn='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_firewall', _modlib_path=modlib_path),\n  File \"/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/nh/8ttzxlg51ngd0cn235m4gsbc0000gn/T/ansible_hetzner.hcloud.hcloud_firewall_payload_kh0ed1__/ansible_hetzner.hcloud.hcloud_firewall_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_firewall.py\", line 344, in <module>\n  File \"/var/folders/nh/8ttzxlg51ngd0cn235m4gsbc0000gn/T/ansible_hetzner.hcloud.hcloud_firewall_payload_kh0ed1__/ansible_hetzner.hcloud.hcloud_firewall_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_firewall.py\", line 338, in main\n  File \"/var/folders/nh/8ttzxlg51ngd0cn235m4gsbc0000gn/T/ansible_hetzner.hcloud.hcloud_firewall_payload_kh0ed1__/ansible_hetzner.hcloud.hcloud_firewall_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_firewall.py\", line 286, in present_firewall\n  File \"/var/folders/nh/8ttzxlg51ngd0cn235m4gsbc0000gn/T/ansible_hetzner.hcloud.hcloud_firewall_payload_kh0ed1__/ansible_hetzner.hcloud.hcloud_firewall_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_firewall.py\", line 230, in _create_firewall\n  File \"/var/folders/nh/8ttzxlg51ngd0cn235m4gsbc0000gn/T/ansible_hetzner.hcloud.hcloud_firewall_payload_kh0ed1__/ansible_hetzner.hcloud.hcloud_firewall_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_firewall.py\", line 231, in <listcomp>\nTypeError: __init__() got an unexpected keyword argument 'description'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by LKaemmerling** [comment]
Hey @rommelfreddy,

please update your hcloud-python version to the latest version: https://github.com/hetznercloud/hcloud-python/releases/tag/v1.16.0

**Comment by rommelfreddy** [comment]
@LKaemmerling push :)

**Comment by LKaemmerling** [comment]
Hey @rommelfreddy,

sorry i was on vacation. You need to update it there where you run the ansible playbook, so your local python version :)

**Comment by rommelfreddy** [comment]
This is fu*king mindblowing :D 

Thank you for your support!
