### ISSUE TITLE
AttributeError: 'Server' object has no attribute 'placement_group' on existing servers

### ISSUE THREAD

**Issue by xoxys** [ansible-collections/hetzner.hcloud#110]
##### SUMMARY
Executing the module on an old existing server seems to result in an issue due to missing placement_group:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'AttributeError' object has no attribute 'message'
fatal: [myserver.example.com -> localhost]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/tmp/ansible_hcloud_server_payload_yuf1_zyk/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 538, in _update_server
      File "/opt/python38/ansible/lib64/python3.8/site-packages/hcloud/core/client.py", line 103, in __getattr__
        value = getattr(self.data_model, name)
    AttributeError: 'Server' object has no attribute 'placement_group'
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "/home/ansibleremote/.ansible/tmp/ansible-tmp-1630844756.0541072-7760-173437027040838/AnsiballZ_hcloud_server.py", line 100, in <module>
        _ansiballz_main()
      File "/home/ansibleremote/.ansible/tmp/ansible-tmp-1630844756.0541072-7760-173437027040838/AnsiballZ_hcloud_server.py", line 92, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/ansibleremote/.ansible/tmp/ansible-tmp-1630844756.0541072-7760-173437027040838/AnsiballZ_hcloud_server.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server', init_globals=dict(_module_fqn='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server', _modlib_path=modlib_path),
      File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_hcloud_server_payload_yuf1_zyk/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 739, in <module>
      File "/tmp/ansible_hcloud_server_payload_yuf1_zyk/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 720, in main
      File "/tmp/ansible_hcloud_server_payload_yuf1_zyk/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 662, in present_server
      File "/tmp/ansible_hcloud_server_payload_yuf1_zyk/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 589, in _update_server
    AttributeError: 'AttributeError' object has no attribute 'message'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.4] 
  config file = /home/ansibleremote/ansible-dc/ansible.cfg
  configured module search path = ['/home/ansibleremote/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/python38/ansible/lib64/python3.8/site-packages/ansible
  ansible collection location = /home/ansibleremote/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/python38/ansible/bin/ansible
  python version = 3.8.6 (default, Oct 27 2020, 09:13:12) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /opt/python38/ansible/lib64/python3.8/site-packages/ansible_collections
Collection     Version
-------------- -------
hetzner.hcloud 1.6.0  

# /opt/python38/ansible/lib/python3.8/site-packages/ansible_collections
Collection     Version
-------------- -------
hetzner.hcloud 1.6.0  
```

**Comment by xoxys** [comment]
Nvm... Don't forget to update the underlying `hcloud-python` package :facepalm:
