### ISSUE TITLE
hcloud_server_info module crashes on IPv6-only servers

### ISSUE THREAD

**Issue by lrsksr** [ansible-collections/hetzner.hcloud#142]
##### SUMMARY

The hcloud_server_info module crashes when among the returned servers, there is one with only an IPv6 primary IP assigned.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`hcloud_server_info`

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.1]
…
  python version = 3.10.5 (main, Jun  9 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection     Version
-------------- -------
hetzner.hcloud 1.8.1
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(…/tmp/local/ansible.cfg) = ['~/.ansible/collections']
```

##### OS / ENVIRONMENT

Fedora 35

##### STEPS TO REPRODUCE

1. Create a server that only has an IPv6 primary IP assigned (no IPv4)
2. Query that servers information with the `hcloud_server_info` module

```yaml
- name: Test hcloud_server_info
  hosts: [ all ]
  collections:
    - hetzner.hcloud
  tasks:
    - name: Create server
      hetzner.hcloud.hcloud_server:
        api_token: "{{ vault_hetzner_api_token }}"
        name: "{{ hetzner_server_name }}"
        enable_ipv4: false
      delegate_to: localhost
    - name: test
      hetzner.hcloud.hcloud_server_info:
        api_token: "{{ vault_hetzner_api_token }}"
        name: "{{ hetzner_server_name }}"
      delegate_to: localhost
  vars:
    hetzner_server_name: testserver
```

##### EXPECTED RESULTS

```
ok: [testserver] => {
    "hetzner_info": {
        "changed": false,
        "failed": false,
        "hcloud_server_info": [
            {
                "backup_window": "14-18",
                "datacenter": "fsn1-dc14",
                "delete_protection": true,
                "id": "123456789",
                "image": "debian-11",
                "ipv4_address": null,
                "ipv6": "2a01:4f8:c0ff:eeee::/64",
                "labels": {},
                "location": "fsn1",
                "name": "testserver",
                "placement_group": null,
                "rebuild_protection": true,
                "rescue_enabled": false,
                "server_type": "cx11",
                "status": "running"
            }
        ]
    }
}
```

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/home/lars/.ansible/tmp/ansible-tmp-1657636699.3450751-1374802-156387222337291/AnsiballZ_hcloud_server_info.py", line 107, in <module>
    _ansiballz_main()
  File "/home/lars/.ansible/tmp/ansible-tmp-1657636699.3450751-1374802-156387222337291/AnsiballZ_hcloud_server_info.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/lars/.ansible/tmp/ansible-tmp-1657636699.3450751-1374802-156387222337291/AnsiballZ_hcloud_server_info.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server_info', init_globals=dict(_module_fqn='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server_info', _modlib_path=modlib_path),
  File "/usr/lib64/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_hetzner.hcloud.hcloud_server_info_payload_6o9w294w/ansible_hetzner.hcloud.hcloud_server_info_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server_info.py", line 232, in <module>
  File "/tmp/ansible_hetzner.hcloud.hcloud_server_info_payload_6o9w294w/ansible_hetzner.hcloud.hcloud_server_info_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server_info.py", line 217, in main
  File "/tmp/ansible_hetzner.hcloud.hcloud_server_info_payload_6o9w294w/ansible_hetzner.hcloud.hcloud_server_info_payload.zip/ansible_collections/hetzner/hcloud/plugins/module_utils/hcloud.py", line 63, in get_result
  File "/tmp/ansible_hetzner.hcloud.hcloud_server_info_payload_6o9w294w/ansible_hetzner.hcloud.hcloud_server_info_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server_info.py", line 159, in _prepare_result
AttributeError: 'NoneType' object has no attribute 'ip'
```

I guess this would have been caught if the CI pipeline was working, but it's broken for more than a year now.
In recent pipeline I couldn't find the module being tested, so I think it fails before it reaches this modules tests.

**Comment by LKaemmerling** [comment]
Hey @lrsksr,

thanks for this report, this was overseen while implementing the flexible network functionality. I will fix it asap and release a bugfix. 

> I guess this would have been caught if the CI pipeline was working, but it's broken for more than a year now.
In recent pipeline I couldn't find the module being tested, so I think it fails before it reaches this modules tests

All tests worked fine, however there is (because of the overseen changes) no test for servers with flexible networks. Why do you think it is "broken"?  As you can see here: https://github.com/ansible-collections/hetzner.hcloud/pulls?q=is%3Apr+is%3Aclosed all tests passed in the last couple MRs and those test basically all modules.

**Comment by arosenhagen** [comment]
Hey @LKaemmerling

this one fixes the hcloud_server_info command - but the hcloud ansible inventory still fails when there's no ipv4 on the server:

`[WARNING]:  * Failed to parse hcloud.yml with ansible_collections.hetzner.hcloud.plugins.inventory.hcloud
plugin: 'NoneType' object has no attribute 'ip'
  File "/usr/local/lib/python3.9/site-packages/ansible/inventory/manager.py", line 289, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/Users/XX/.ansible/collections/ansible_collections/hetzner/hcloud/plugins/inventory/hcloud.py", line 283, in parse
    self._set_server_attributes(server)
  File "/Users/XX/.ansible/collections/ansible_collections/hetzner/hcloud/plugins/inventory/hcloud.py", line 219, in _set_server_attributes
    self.inventory.set_variable(server.name, "ansible_host", to_native(server.public_net.ipv4.ip))
[WARNING]: Unable to parse hcloud.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available`

Can we expect to have a v1.8.2 anytime soon?

**Comment by LKaemmerling** [comment]
Hey @arosenhagen,

this is not a bug, per default ansible specify to use the ipv4 as host. You should specify `connect_with: hostname`.
