### ISSUE TITLE
[issue] Creating server results in error 404

### ISSUE THREAD

**Issue by Synt3x** [ansible-collections/hetzner.hcloud#223]
##### SUMMARY
When trying to use this collection in our playbook, me and my co-worker both receives error 404. This collection have worked in the past for us, but now it seems like something have changed. 

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
```bash
ansible [core 2.15.0]
  config file = /home/rl/infra/ansible/ansible.cfg
  configured module search path = ['/home/rl/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/rl/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
hetzner.hcloud                1.12.0 
hetzner.hcloud                1.11.0 
```

##### OS / ENVIRONMENT
Windows 10, WSL, Ubuntu 22.04, WSL

##### STEPS TO REPRODUCE
If you need further details, please let me know.
```yaml
    - name: Create new server
      hcloud_server:
        api_token: "{{ hetzner_token }}"
        location: hel1
        name: "{{ hostname }}"
        server_type: "{{ server_type }}"
        image: ubuntu-22.04
        state: present
        firewalls:
          - icmp
        user_data: "{{ user_data }}"
        ssh_keys:
          - fake
        volumes: "{{ new_volume.hcloud_volume.id | default([]) }}"
      register: new_server
```

##### EXPECTED RESULTS
Server is created on Hetzner infrastructure.

##### ACTUAL RESULTS
Receiving an exception `hcloud.hcloud.APIException: 404 Not Found`.

```python
The full traceback is:
Traceback (most recent call last):
  File "/home/rl/.ansible/tmp/ansible-tmp-1687177217.6431222-3293-147830831878474/AnsiballZ_hcloud_server.py", line 107, in <module>
    _ansiballz_main()
  File "/home/rl/.ansible/tmp/ansible-tmp-1687177217.6431222-3293-147830831878474/AnsiballZ_hcloud_server.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/rl/.ansible/tmp/ansible-tmp-1687177217.6431222-3293-147830831878474/AnsiballZ_hcloud_server.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server', init_globals=dict(_module_fqn='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server', _modlib_path=modlib_path),
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_hcloud_server_payload_4fjt7ru4/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 927, in <module>
  File "/tmp/ansible_hcloud_server_payload_4fjt7ru4/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 908, in main
  File "/tmp/ansible_hcloud_server_payload_4fjt7ru4/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 843, in present_server
  File "/tmp/ansible_hcloud_server_payload_4fjt7ru4/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 458, in _create_server
  File "/usr/local/lib/python3.10/dist-packages/hcloud/firewalls/client.py", line 209, in get_by_id
    response = self._client.request(
  File "/usr/local/lib/python3.10/dist-packages/hcloud/hcloud.py", line 240, in request
    self._raise_exception_from_json_content(json_content)
  File "/usr/local/lib/python3.10/dist-packages/hcloud/hcloud.py", line 204, in _raise_exception_from_json_content
    raise APIException(
hcloud.hcloud.APIException: 404 Not Found
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/rl/.ansible/tmp/ansible-tmp-1687177217.6431222-3293-147830831878474/AnsiballZ_hcloud_server.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/rl/.ansible/tmp/ansible-tmp-1687177217.6431222-3293-147830831878474/AnsiballZ_hcloud_server.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/rl/.ansible/tmp/ansible-tmp-1687177217.6431222-3293-147830831878474/AnsiballZ_hcloud_server.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server', init_globals=dict(_module_fqn='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_server', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_hcloud_server_payload_4fjt7ru4/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 927, in <module>\n  File \"/tmp/ansible_hcloud_server_payload_4fjt7ru4/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 908, in main\n  File \"/tmp/ansible_hcloud_server_payload_4fjt7ru4/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 843, in present_server\n  File \"/tmp/ansible_hcloud_server_payload_4fjt7ru4/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 458, in _create_server\n  File \"/usr/local/lib/python3.10/dist-packages/hcloud/firewalls/client.py\", line 209, in get_by_id\n    response = self._client.request(\n  File \"/usr/local/lib/python3.10/dist-packages/hcloud/hcloud.py\", line 240, in request\n    self._raise_exception_from_json_content(json_content)\n  File \"/usr/local/lib/python3.10/dist-packages/hcloud/hcloud.py\", line 204, in _raise_exception_from_json_content\n    raise APIException(\nhcloud.hcloud.APIException: 404 Not Found\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by jooola** [comment]
Hello @Synt3x,

Did you create a firewall named `icmp` before creating the server ? The `firewalls` list takes either the IDs or the names of firewalls that you want to apply to the server.

The error you are hitting is that the firewall named `icmp` does not exist. We first try to query the firewall by name, we don't find anything, and therefore we try to query a firewall by ID (`/firewalls/{id}`). This last call results in 404.

The error message is definitely misleading, but this should be fixed in the next release.

**Comment by Synt3x** [comment]
Hello @jooola thanks for the replay! You are correct, the name on our firewall rule was changed. Everything now seems to work as expected.

Thanks!
