### ISSUE TITLE
Cant set ssh_keys list in hcloud_server

### ISSUE THREAD

**Issue by denzs** [ansible-collections/hetzner.hcloud#66]
##### SUMMARY

The module hcloud_server works like a charm for me, but when i add
```
    ssh_keys:
      - foo@bar
```
to my playbook ansible fails like shown at the end.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

hcloud_server

##### ANSIBLE VERSION

```
  config file = /home/ixyd/dev/videobridge-deployment/ansible.cfg
  configured module search path = ['/home/ixyd/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.1+ (default, Feb  5 2021, 13:46:56) [GCC 10.2.1 20210110]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/ixyd/dev/videobridge-deployment/ansible.cfg) = True
CACHE_PLUGIN(/home/ixyd/dev/videobridge-deployment/ansible.cfg) = yaml
CACHE_PLUGIN_CONNECTION(/home/ixyd/dev/videobridge-deployment/ansible.cfg) = tmp
COLLECTIONS_PATHS(/home/ixyd/dev/videobridge-deployment/ansible.cfg) = ['/home/ixyd/dev/videobridge-deployment/collections']
DEFAULT_HOST_LIST(/home/ixyd/dev/videobridge-deployment/ansible.cfg) = ['/home/ixyd/dev/videobridge-deployment/inventories/dev']
INTERPRETER_PYTHON(/home/ixyd/dev/videobridge-deployment/ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT

Debian testing/unstable ;)

##### STEPS TO REPRODUCE

```yaml
- name: create nodes
  hcloud_server:
    api_token: ******
    name: "{{ item }}"
    server_type: "{{ shard.machine_type }}"
    image: ubuntu-20.04
    location: "{{ shard.location }}"
    ssh_keys:
      - foo@bar
    labels:
      env: dev
      shard: "{{ shard.desc }}"
    state: present
  with_sequence: start=1 count={{ shard.machines }} format={{ env }}.{{ shard.desc }}.jvb%d
  register: server

```
SSH-Key is uploaded and api_token is replaced by correct value of course.
When the two lines regarding ssh are removed, it works perfect.

##### EXPECTED RESULTS

No python failures and ssh key gets deployed successfully.

##### ACTUAL RESULTS

```
TASK [create node] *********************************************************************************************************************************************************************************************************************************
task path: /home/ixyd/dev/videobridge-deployment/nested_loop.yml:2
redirecting (type: modules) ansible.builtin.hcloud_server to hetzner.hcloud.hcloud_server
Including module_utils file ansible/__init__.py
Including module_utils file ansible/module_utils/__init__.py
Including module_utils file ansible/module_utils/_text.py
Including module_utils file ansible/module_utils/basic.py
Including module_utils file ansible/module_utils/common/_collections_compat.py
Including module_utils file ansible/module_utils/common/__init__.py
Including module_utils file ansible/module_utils/common/_json_compat.py
Including module_utils file ansible/module_utils/common/_utils.py
Including module_utils file ansible/module_utils/common/file.py
Including module_utils file ansible/module_utils/common/parameters.py
Including module_utils file ansible/module_utils/common/collections.py
Including module_utils file ansible/module_utils/common/process.py
Including module_utils file ansible/module_utils/common/sys_info.py
Including module_utils file ansible/module_utils/common/text/converters.py
Including module_utils file ansible/module_utils/common/text/__init__.py
Including module_utils file ansible/module_utils/common/text/formatters.py
Including module_utils file ansible/module_utils/common/validation.py
Including module_utils file ansible/module_utils/common/warnings.py
Including module_utils file ansible/module_utils/compat/selectors.py
Including module_utils file ansible/module_utils/compat/__init__.py
Including module_utils file ansible/module_utils/compat/_selectors2.py
Including module_utils file ansible/module_utils/distro/__init__.py
Including module_utils file ansible/module_utils/distro/_distro.py
Including module_utils file ansible/module_utils/parsing/convert_bool.py
Including module_utils file ansible/module_utils/parsing/__init__.py
Including module_utils file ansible/module_utils/pycompat24.py
Including module_utils file ansible/module_utils/six/__init__.py
Including module_utils file ansible_collections/hetzner/hcloud/plugins/module_utils/hcloud.py
Including module_utils file ansible/module_utils/ansible_release.py
Including module_utils file ansible_collections/__init__.py
Including module_utils file ansible_collections/hetzner/__init__.py
Including module_utils file ansible_collections/hetzner/hcloud/__init__.py
Including module_utils file ansible_collections/hetzner/hcloud/plugins/__init__.py
Including module_utils file ansible_collections/hetzner/hcloud/plugins/module_utils/__init__.py
Using module file /home/ixyd/dev/videobridge-deployment/collections/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py
Pipelining is enabled.
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ixyd
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_hcloud_server_payload_i8nc04ea/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 616, in <module>
  File "/tmp/ansible_hcloud_server_payload_i8nc04ea/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 597, in main
  File "/tmp/ansible_hcloud_server_payload_i8nc04ea/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 540, in present_server
  File "/tmp/ansible_hcloud_server_payload_i8nc04ea/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 333, in _create_server
  File "/tmp/ansible_hcloud_server_payload_i8nc04ea/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py", line 334, in <listcomp>
TypeError: 'NoneType' object is not callable
failed: [localhost] (item=dev.shard1.jvb1) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "dev.shard1.jvb1",
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_hcloud_server_payload_i8nc04ea/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 616, in <module>\n  File \"/tmp/ansible_hcloud_server_payload_i8nc04ea/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 597, in main\n  File \"/tmp/ansible_hcloud_server_payload_i8nc04ea/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 540, in present_server\n  File \"/tmp/ansible_hcloud_server_payload_i8nc04ea/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 333, in _create_server\n  File \"/tmp/ansible_hcloud_server_payload_i8nc04ea/ansible_hcloud_server_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_server.py\", line 334, in <listcomp>\nTypeError: 'NoneType' object is not callable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```
If there is anything i can do to help with further debugging just let me know!

**Comment by vitamindit** [comment]
I probably had the same problem today. Your stacktrace looks familiar to me anyway :)

In my case, a too old version of the hcloud-python module has been imported, incompatible with the current version 1.3.1, of the hcloud ansible collection.

To check this, you could add the following task to your playbook and verify the output - that the current hcloud-python module 1.11 is used.

    - name: "Show hcloud module path / file."
      command: "python3 -c \"import hcloud as _; print(_.__file__)\""

**Comment by vitamindit** [comment]
I probably had the same problem today. Your stacktrace looks familiar to me anyway :)

In my case, a too old version of the hcloud-python module has been imported, incompatible with the current version 1.3.1, of the hcloud ansible collection.

To check this, you could add the following task to your playbook and verify the output ... that the current hcloud-python module 1.11 is used.

    - name: "Show hcloud module path / file."
      command: "python3 -c \"import hcloud as _; print(_.__file__)\""

**Comment by denzs** [comment]
Thank you so much!
Updating the hcloud module via pip fixed it. :+1:
